#!/bin/sh -e

case "$1" in
  configure)
    # first install
    if [ "$2" == "" ]; then
      # detect device
      /usr/bin/yavdr-detect-sound-device
    fi

    # temlate files
    /usr/bin/yavdr-template-sound
  ;;

esac

exit 0
