#!/bin/sh -e

case "$1" in
  configure)
    # detect device
    /usr/bin/yavdr-detect-sound-device --first-only

    # temlate files
    /usr/bin/process-template --owner root --group root --mode 0644 /etc/asound.conf
    /usr/bin/process-template --owner root --group root --mode 0644 /etc/init/sound-device.conf
  ;;

esac

exit 0
