#!/bin/sh -e

case "$1" in
  configure)
    # first install
    if [ "$2" == "" ]; then
      # detect device
      /usr/bin/yavdr-detect-sound-device
    fi

    # temlate files
    /usr/bin/process-template --owner root --group root --mode 0644 /etc/asound.conf
    /usr/bin/process-template --owner root --group root --mode 0644 /etc/init/sound-device.conf
  ;;

esac

exit 0
