#!/bin/bash -e

export LC_MESSAGES=C
export LANG=C

# iterate all interfaces
for INTERFACE in hdmi digital analog ; do

  # init
  CARD=""
  DEVICE=""
  FOUNDED=$(aplay -l | grep -i $INTERFACE | wc -l)

  # check for hardware
  # 1 founded
  if [ $FOUNDED -eq 1 ]; then
    SINK="$(aplay -l | grep -i $INTERFACE)"

    # get the index id's
    CARD=${SINK//card } ; CARD=${CARD%%:*}
    DEVICE=${SINK//*device }; DEVICE=${DEVICE%%:*}

    # put them into db
    /usr/bin/yavdr-db -a write -k system.alsa.${INTERFACE}.card -v $CARD
    /usr/bin/yavdr-db -a write -k system.alsa.${INTERFACE}.device -v $DEVICE

  # 4 founded
  elif [ $FOUNDED -eq 4 ]; then

    CARD=$(LANG=C aplay -l | grep -i $INTERFACE) ; CARD=${CARD//:*} ; CARD=${CARD#card }
    ELD="`grep -e "monitor_present.*1$" /proc/asound/card${CARD}/eld* | cut -d":" -f1`"
    if [ "x$ELD" != "x" ]; then
      ELD=${ELD#*\#} ; ELD=${ELD//.*}
      DEVICE=$(grep -e "^ *Device:.*" /proc/asound/card$CARD/codec\#${ELD})
      DEVICE=${DEVICE#*device=}
      # put them into db
      /usr/bin/yavdr-db -a write -k system.alsa.${INTERFACE}.card -v $CARD
      /usr/bin/yavdr-db -a write -k system.alsa.${INTERFACE}.device -v $DEVICE
    else
      # we are totally lost and need to do some wild guessing
      /usr/bin/yavdr-db -a write -k system.alsa.${INTERFACE}.card -v $CARD
      /usr/bin/yavdr-db -a write -k system.alsa.${INTERFACE}.device -v 7
    fi

  fi
done

# set sound type
if [ "$(dbget system.sound.type)" = "" ]; then
  if [ "$(dbget system.alsa.hdmi.device)"    != "" -a \
    "$(dbget system.alsa.digital.device)" != "" -a \
    "$(dbget system.alsa.analog.device)"  != "" ]; then
    /usr/bin/yavdr-db -a write -k system.sound.type -v all
  elif  [ "$(dbget system.alsa.hdmi.device)"    != "" ]; then
    /usr/bin/yavdr-db -a write -k system.sound.type -v hdmi
  elif  [ "$(dbget system.alsa.digital.device)" != "" ]; then
    /usr/bin/yavdr-db -a write -k system.sound.type -v digital
  else
    /usr/bin/yavdr-db -a write -k system.sound.type -v analog
  fi
fi

# unmute
alsaunmute
